# Generated by Django 4.1.3 on 2022-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Role', models.CharField(max_length=100)),
                ('date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
